### ISSUE TITLE
Problems with polling on (many) dynamic attributes

### ISSUE THREAD

**Issue by mkomel** [tango-controls/cppTango#482]
We have encountered some problems with setting polling on a device server with many dynamic attributes. We are trying this with prerelease version of Tango 9.3.2 (on Ubuntu 18.04.1), since 9.2.5 has a known problem with setting polling to dyn.attributes (#463). 
When first importing a device server (with many dyn.attributes) into the database and starting it, it can take excesively long time for the device server to become operational (e.g. until it outputs "Ready to accept request"). For example with 300 dynamic attribute instances, it can take several minutes.
On any subsequent device server start, the startup time becomes normal (a few seconds).

We have also seen segfaults happenning occasionally on restart action. These segfaults seem to be dependent on the number of dynamic attributes instances (e.g. with only a few dyn.attributes they never happened, with lots of dyn.attributes they happen sporadically).

As a test, we have created a simple dummy device server which creates 300 dynamic attributes (can be tweaked via num_attributes property): 
[dynattributesdevice.zip](https://github.com/tango-controls/cppTango/files/2348403/dynattributesdevice.zip)
- Use populate.py script to import the device server to the database.
- Afterwards start the device server and observe a lengthy startup time. During this initial startup mysqld process runs with a very high CPU utilization.
- Stop and start the device server again. Observe that the startup time is now normal.
- Change/add a device property named "num_attributes" to 1000 and restart the device server (via Jive). Device server becomes unresponsive for ~10minutes. During that time there is no indication of what is going on, nor is there any indication of when the device server becomes responsive again.
- Restart the device server again (via Jive). Observe a Tango error popup "Device (...) timed out (>3000 ms)!" each time the device server restart is done.
- segfault is hard to reproduce with this test DS. The following occasionally trigerred it:  stop the device server (Ctrl-C), set property "num_attributes" to some value a bit lower than the previous one. Start the device server and after it finishes the initialization stop it (Ctrl-C). Occasionally segfault happens at this point.
With this test device server we were unable to reproduce segfault on restart action (via Jive), though.

Note that none of the above issues happen when there is no polling set on the attributes.

**Comment by bourtemb** [comment]
Hi Matej,
Thanks for the report. I played a bit with the device server you provided and I think I understand why this is so slow in this specific case.
The dynamic attributes created by this device server are all polled at 3 seconds.
The first time the attributes are created, Tango will configure the polling for these attributes.
During this process, polled_attr system property is created and updated. You can see this property in jive by selecting "Show system property" in the edit menu. Then when you click on the properties of your devices, you will see this polled_attr property.
In your specific case, when you configure your device to create 1000 attributes, this property is a big property because 1000 attributes are listed here.
There are several factors which are making the startup process very slow in this specific case.
The first factor is the fact that this property is written every time the polling is started for the first time on a new attribute.
So, with 1000 attributes, this property is updated at least 1000 times during the startup process.
To give you a idea of this process, you can have a look at this screenshot of the history of this polled_attr system property when DynAttrDeviceServer is configured with num_attributes = 5:
![polled_attr_history](https://user-images.githubusercontent.com/16306867/45204172-b5c4d800-b27e-11e8-9987-f7910710baf6.png)
As you can see, this property is updated many times in a short period of time.
The main performance issue is actually coming from the fact that we can see the history of this property.
Every time this property is updated, there is a new entry in its history (another table in the Tango database). In our control system for instance, it is configured to keep the last 10 updates in the history.
If the history is already full (10 items), a new entry is added and the oldest one is deleted.
So I think you start to see what's going on in your specific case...
MySQL is busy writing this big attr_polled property and maintaining its history.
The second time you start your device server, this property is already in the database with the final value so you don't get this performance problem again.
