### ISSUE TITLE
Segmentation fault after command_inout_reply

### ISSUE THREAD

**Issue by elkinvg** [tango-controls/cppTango#494]
Segmentation fault after command_inout_reply.

Tango 9.2.5
OmniORB 4.2.1
0MQ 4.3.1

Test device here https://github.com/elkinvg/TangoServerMultiDevsTest 
Zip: (https://github.com/elkinvg/TangoServerMultiDevsTest/archive/master.zip)

crash conditions:
	1. Several devices are used in the server (to speed up ... for Example 10).
	2. Used commands from remote device with a long duration. (In here is "STATE". In my case, duration more than 500ms about once in 10 seconds)
	3. Used command_inout_asynch
	4. A small timeout is set (in here is 500ms)

Crash in TangoServerMultDevs.cpp:296

```cpp
outputCom = testProxy->command_inout_reply(requestState_id);
```

The crash did not immediately. After 30000 and more calls the polling method.

**Comment by bourtemb** [comment]
Hi,

This is a known bug which is present in the omniORB version you are using.
It can be fixed easily by applying the omniORB patch documented here:
https://tango-controls.readthedocs.io/en/latest/installation/patches.html#version-9-2-5-source-patches

Direct link to the patch:
http://ftp.esrf.fr/pub/cs/tango/Patches/dii_race.patch

This bug has been fixed in omniORB 4.2.2 so you can also use this version of omniORB.
