### ISSUE TITLE
Possible error in WAttribute::rollback()

### ISSUE THREAD

**Issue by udyni** [tango-controls/cppTango#541]
As I was trying to understand how to recover the memorized value of an attribute, I noticed that in WAttribute::rollback() at line 2647 of w_attribute.cpp the rollback of type UShort is instead rolling back the value for data type Double.

Best regards
Michele

**Comment by bourtemb** [comment]
Well spotted, @udyni 
Thank you very much for the bug report!

**Comment by bourtemb** [comment]
@udyni , did you get annoyed by this bug somehow or did you simply see this bug by reading the code?
In the first case, can you describe your use case and also the behaviour you were observing when the bug occurred?

**Comment by udyni** [comment]
I was studying the code to understand where the memorized attributes were
read from the database and set in the attribute write value and just
noticed the error in the code.

**Comment by bourtemb** [comment]
After analyzing the source code and doing some simple tests, it looks like this bug can affect the users using WRITE DevUShort attributes (No impact on READ and READ_WRITE attributes it seems).
When an exception is thrown when trying to write the WRITE attribute, the set value is not rolled back correctly in some specific cases (exception in device server write method associated to this attribute, exception thrown because it is not allowed to write this attribute in the current state, exception in read_attr_hardware()).

**Comment by bourtemb** [comment]
Thanks again for the bug report @udyni 
This issue should be fixed in #542
