### ISSUE TITLE
Raise required C++11 and cmake versions

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#626]
As decided today the we will nowish require C++11 and cmake 3.7 on the tango-9-lts branch. A C++14 supported compiler will be required around 8/2020. In practical terms this means we will require at least gcc 4.8.1, [link](https://gcc.gnu.org/projects/cxx-status.html), or clang 3.3. [link](https://clang.llvm.org/cxx_status.html#cxx11).

For the supported linux distributions this means we will not build on wheezy anymore. The windows builds should not be affected, as MSVC 2015 already supports C++11, see https://devblogs.microsoft.com/cppblog/c111417-features-in-vs-2015-rtm/.

It would be nice to add some docker images for other required linux distributions (centos, ubuntu lts, ...) so that we can check that we at least build on these. But I need to know which versions I should add.

**Comment by bourtemb** [comment]
> For the supported linux distributions this means we will not build on wheezy anymore. The windows builds should not be affected, as MSVC 2015 already supports C++11, see https://devblogs.microsoft.com/cppblog/c111417-features-in-vs-2015-rtm/.

Some appveyor build will fail, because they are using the Visual Studio 2015 appveyor image, but the code is compiled with msvc9, msvc10 and msvc-12 too.

I think time has come to apply (Except in 9.3-backports branch) what has been decided during the Tango Kernel Meeting which took place at Solaris (See the [minutes](https://github.com/tango-controls/tango-kernel-followup/blob/master/2019-02-04/outcomes.md)):

> Decision was taken to stop support for MSVC9, MSVC10 and MSVC12. The builds for these MSVC compiler versions will be removed from appveyor. If some users still need to compile cppTango using these compilers, they will need to fork cppTango and maintain a version compatible with these old compilers.
