### ISSUE TITLE
Add CI job with alpline linux

### ISSUE THREAD

**Issue by t-b** [tango-controls/cppTango#799]
SKA is using tango in docker using a angstrom linux [1]. As this linux also uses a different libc, musl, it would be nice to get a CI job for testing. We can use alpine for that, this is also common to use for docker and has musl as well.

Obstacles:
- [ ] We need to compile omniORB ourselves

[1]: https://github.com/tango-controls/cppTango/issues/767#issuecomment-697951661

**Comment by mliszcz** [comment]
> Obstacles:
> 
>     * [ ]  We need to compile omniORB ourselves

I wouldn't expect much trouble here. Last time I compiled omniORB on alpine (I think 3.11) standard `./configure && make install` approach worked without any problems, So it's basically four extra lines in our dockerfiles (including wget + tar calls). If compilation time turns out to be a problem, we may consider putting image with pre-built omniORB into our dockerhub and using that as a base for CI tests.
